### PR TITLE
fix: vue2 tsx (class component) hmr exception

### PR DESCRIPTION
**Pull request by sun0day**
fixes https://github.com/vitejs/vite/issues/11008

See https://github.com/vitejs/vite/pull/11059

### CODE REVIEW

**Comment by sun0day** [comment]
@sodatea  cc

**Review by sodatea — CHANGES_REQUESTED** [review]
Please don't include unrelated style changes in the PR

**Comment by sun0day** [comment]
> Please don't include unrelated style changes in the PR

Done.

**Review by sodatea — APPROVED** [review]
Thanks!

**Pull request merged**
